web/main/urls.py
from django.urls import URLPattern, path
from main.views import equipment_views, port_views, vlan_views, views


app_name = 'main'
urlpatterns = [
    path('', views.index, name='index'),
    path('<slug:autozal_slug>/', views.autozal, name='autozal'),
    path('<slug:autozal_slug>/<int:rack_number>/', views.rack, name='rack'),
    path('<slug:autozal_slug>/<int:rack_number>/<str:place>', views.equipment, name='equipment-detail'),

    path('vlan/<slug:complex>/', views.vlan, name='vlan'),

    path('edit/equipment-add/', equipment_views.EquipmentAddView.as_view(), name='equipment-add'),
    path('edit/equipment-update/<int:pk>/', equipment_views.EquipmentUpdateView.as_view(), name='equipment-update'),
    path('edit/equipment-delete/<int:pk>/', equipment_views.EquipmentDeleteView.as_view(), name='equipment-delete'),

    path('edit/port-update/<int:pk>', port_views.port_update, name='port-update'),
    path('edit/port-clear/', port_views.port_clear, name='port-clear'),

    path('edit/vlan-add/', vlan_views.VlanAddView.as_view(), name='vlan-add'),
    path('edit/vlan-update/<int:pk>/', vlan_views.VlanUpdateView.as_view(), name='vlan-update'),
    path('edit/vlan-delete/<int:pk>/', vlan_views.VlanDeleteView.as_view(), name='vlan-delete'),

    path('ajax/port-dest/equip', port_views.get_equip_dropdown, name='port-dest-equip'),
    path('ajax/port-dest/ports', port_views.get_port_dropdown, name='port-dest-ports'),
]

web/main/templates/main/autozal.html
{% extends 'main/base.html' %}

{% block content %}
<h1 class="h3 mb-2 text-gray-800">{{ autozal.name }}</h1>
<p class="mb-1">{{ autozal.desc }}</p>
<div class="row">
    <div class="col-4">
        <table class="table table-bordered table-striped mt-3">
            <thead class="thead-dark">
              <tr>
                <th scope="col" colspan="2" class="text-center">Телекоммуникационные шкафы</th>
              </tr>
            </thead>
            <tbody>
                <!-- перебираем все ТШ в автозале -->
                {% for rack in autozal.racks.all %}
                <tr>
                    <th scope="row" class="text-center align-middle">ТШ {{ rack.number }}</th>
                    <td class="text-center">
                        <a href="{% url 'main:rack' rack.autozal.slug rack.number %}" class="btn btn-primary"><i class="fas fa-arrow-right"></i></a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock content %}

web/main/templates/main/index.html
{% extends 'main/base.html' %}

{% block content %}
<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-center mb-5">
    <h1 class="h3 mb-0 text-gray-800">Добро пожаловать!</h1>
</div>

<!-- Content Row -->
<div class="row justify-content-md-center">
    {% for autozal in autozals %}
    <div class="col-xl-5 col-md-6 mb-4">
        <a href="{% url 'main:autozal' autozal.slug %}">
            <div class="card border-bottom-primary shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                {{ autozal.desc }}</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">{{ autozal.name }}</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-server fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </a>
    </div>
    {% endfor %}
</div>
{% endblock content %}

web/main/templates/main/rack.html
{% extends 'main/base.html' %}

{% block content %}
<h1 class="h3 mb-2 text-gray-800">ТШ {{ rack.number }}</h1>

<!-- табы для оборудования и фоток-->
<ul class="nav nav-tabs" id="myTab" role="tablist">
    <li class="nav-item" role="presentation">
        <a class="nav-link active" id="equip-tab" data-toggle="tab" href="#equip" role="tab" aria-controls="equip" aria-selected="true">Оборудование</a>
    </li>
    <li class="nav-item" role="presentation">
        <a class="nav-link" id="photo-tab" data-toggle="tab" href="#photo" role="tab" aria-controls="photo" aria-selected="false">Фото</a>
    </li>
</ul>
<div class="tab-content" id="myTabContent">
    <!-- Таб для оборудования-->
    <div class="tab-pane fade mt-3 show active" id="equip" role="tabpanel" aria-labelledby="equip-tab">
        <table class="table table-responsive table-bordered table-striped mt-3">
            <thead class="thead-dark">
                <tr>
                <th scope="col" class="text-center">Place</th>
                    <th scope="col">Name</th>
                    <th scope="col">Owner</th>
                    <th scope="col">Description</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                <!-- перебор оборудования в стойке отсортированного по месту -->
                {% for equip in rack.equipment.all|dictsort:"place" %}
                <tr>
                    <th scope="row" class="text-center">{{ equip.place }}</th>
                    <td>{{ equip.name }}</td>
                    <td>{{ equip.owner }}</td>
                    <td>{{ equip.desc }}</td>
                    <td class="text-center">
                        <!-- GET аргументы для того, чтобы передать в suссess_url нужные параметры -->
                        <a href="{% url 'main:equipment-update' equip.id %}?autozal_slug={{ rack.autozal.slug }}&rack_number={{ rack.number }}" class="btn-sm btn-circle btn-warning">
                            <i class="fas fa-pen"></i>
                        </a>
                        <a href="{% url 'main:equipment-detail' equip.rack.autozal.slug equip.rack.number equip.place %}" class="btn-sm btn-circle btn-primary"><i class="fas fa-arrow-right"></i></a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
            
        </table>
        <!-- GET аргументы для того, чтобы передать в suссess_url нужные параметры -->
        <a href="{% url 'main:equipment-add'%}?autozal_slug={{ rack.autozal.slug }}&rack_number={{ rack.number }}" class="btn btn-primary text-right">Добавить <i class="fas fa-plus ml-2"></i></a>
    </div>
    <!-- Таб для фоток-->
    <div class="tab-pane fade mt-3" id="photo" role="tabpanel" aria-labelledby="photo-tab">
        Фото
    </div>
</div>
{% endblock content %}

                                                                        
            