web/main/urls.py
from django.urls import URLPattern, path
from main.views import equipment_views, port_views, vlan_views, views


app_name = 'main'
urlpatterns = [
    path('', views.index, name='index'),
    path('<slug:autozal_slug>/', views.autozal, name='autozal'),
    path('<slug:autozal_slug>/<int:rack_number>/', views.rack, name='rack'),
    path('<slug:autozal_slug>/<int:rack_number>/<str:place>', views.equipment, name='equipment-detail'),

    path('vlan/<slug:complex>/', views.vlan, name='vlan'),

    path('edit/equipment-add/', equipment_views.EquipmentAddView.as_view(), name='equipment-add'),
    path('edit/equipment-update/<int:pk>/', equipment_views.EquipmentUpdateView.as_view(), name='equipment-update'),
    path('edit/equipment-delete/<int:pk>/', equipment_views.EquipmentDeleteView.as_view(), name='equipment-delete'),

    path('edit/port-update/<int:pk>', port_views.port_update, name='port-update'),
    path('edit/port-clear/', port_views.port_clear, name='port-clear'),

    path('edit/vlan-add/', vlan_views.VlanAddView.as_view(), name='vlan-add'),
    path('edit/vlan-update/<int:pk>/', vlan_views.VlanUpdateView.as_view(), name='vlan-update'),
    path('edit/vlan-delete/<int:pk>/', vlan_views.VlanDeleteView.as_view(), name='vlan-delete'),

    path('ajax/port-dest/equip', port_views.get_equip_dropdown, name='port-dest-equip'),
    path('ajax/port-dest/ports', port_views.get_port_dropdown, name='port-dest-ports'),
]

web/main/forms/vlan_forms.py
from django.core.exceptions import ValidationError
from django.core.exceptions import NON_FIELD_ERRORS

from django import forms
from ..models import Vlan

# форма добавления редактирования оборудования
class VlanForm(forms.ModelForm):
    class Meta:
        model = Vlan
        fields = '__all__'
        # замена стандартного сообщения об ошибке unique_together
        error_messages = {
            NON_FIELD_ERRORS: {
                'unique_together': "Данный vlan в этом комплексе занят!",
            }
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # прописываем пустое значение вместо '-------' 
        self.fields['complex'].empty_label = 'Выберите комплекс...'
        # каждому полю формы прописываем класс 'form-control'
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['autocomplete'] = 'off'


class VlanUpdateForm(VlanForm):
    class Meta:
        model = Vlan
        fields = '__all__'
        error_messages = {
            NON_FIELD_ERRORS: {
                'unique_together': "Данный vlan в этом комплексе занят!",
            }
        }

web/main/views/vlan_views.py
from os import pread
from django.views.generic.edit import UpdateView, CreateView, DeleteView
from django.urls import reverse_lazy
from django.shortcuts import redirect, render

from ..models import Complex, Vlan
from ..forms.vlan_forms import VlanForm, VlanUpdateForm


# добавление влана
class VlanAddView(CreateView):
    model = Vlan
    template_name = 'main/vlan/vlan-add.html'
    form_class = VlanForm

    # подставляем в форму номер стойки, из которой была нажата кнопка "Добавить"
    def get_initial(self, **kwargs):
        print(self.request.GET)
        initial = super(VlanAddView, self).get_initial(**kwargs)
        initial['complex'] = Complex.objects.get(slug=self.request.GET['complex_slug'])
        return initial
    
    # вытаскиваем GET параметры с номером текущей стойки и slug автозала
    def get_success_url(self, **kwargs):
        return reverse_lazy(
            'main:vlan',
            args=[
                self.request.GET['complex_slug'],
                ]
            )


# редактирование Vlan
class VlanUpdateView(UpdateView):
    model = Vlan
    template_name = 'main/vlan/vlan-update.html'
    form_class = VlanUpdateForm
    context_object_name = 'vlan'

    # вытаскиваем GET параметры со slug комплекса
    def get_success_url(self, **kwargs):
        return reverse_lazy(
            'main:vlan',
            args=[
                self.request.GET['complex_slug'],
                ]
            )


# удаление vlan
class VlanDeleteView(DeleteView):
    model = Vlan
    template_name = 'main/vlan/vlan-delete.html'
    context_object_name = 'vlan'

    # вытаскиваем GET параметры со slug комплекса
    def get_success_url(self, **kwargs):
        return reverse_lazy(
            'main:vlan',
            args=[
                self.request.GET['complex_slug'],
                ]
            )

web/main/templates/main/vlan/vlan-add.html
{% extends 'main/base.html' %}

{% block content %}
<h1 class="h3 mb-3 text-gray-800">Добавить Vlan</h1>
<div class="row">
    <div class="col-12">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <!-- перебираем общие ошибки формы -->
            {% for error in form.non_field_errors %}
            <div class="row mb-2 align-items-center">
                <div class="col-6 alert alert-danger">
                    {{ error }}
                </div>
            </div>
            {% endfor %}
            <!-- перебираем саму форму -->
            {% for field in form %}
            <div class="row mb-2 align-items-center">
                <div class="col-2">
                    <label class="mb-0" for="{{ field.id_for_label }}">{{ field.label }}</label>
                </div>
                <div class="col-4 pr-0">
                    {{ field }}
                </div>
                <div class="col-3 text-center">
                    <!-- перебираем ошибки конкретного поля чтобы задать свои стили -->
                    {% for error in field.errors %}
                    <div class="alert alert-danger mb-0" style="padding: 0.375rem !important">{{ error }}</div>
                    {% endfor %}
                </div>
            </div>
            {% endfor %}
            <div class="row mt-3">
                <div class="col-6 pr-0">
                    <input class="btn btn-block btn-primary" type="submit" value="Добавить">
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

web/main/templates/main/vlan/vlan-delete.html
{% extends 'main/base.html' %}

{% block content %}
<h1 class="h3 mb-3 text-gray-800">Вы действительно хотите удалить Vlan "{{ vlan.vlan_id }}"?</h1>
<form method="post">
    {% csrf_token %}
    <input type="submit" value="Удалить" class="btn btn-danger">
    <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-secondary">Назад</a>
</form>
{% endblock content %}

web/main/templates/main/vlan/vlan-update.html
{% extends 'main/base.html' %}

{% block content %}
<h1 class="h3 mb-3 text-gray-800">Редактировать Vlan "{{ vlan.vlan_id }}"</h1>
<div class="row">
    <div class="col-12">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <!-- перебираем общие ошибки формы -->
            {% for error in form.non_field_errors %}
            <div class="row mb-2 align-items-center">
                <div class="col-6 alert alert-danger">
                    {{ error }}
                </div>
            </div>
            {% endfor %}
            <!-- перебираем саму форму -->
            {% for field in form %}
            <div class="row mb-2 align-items-center">
                <div class="col-2">
                    <label class="mb-0" for="{{ field.id_for_label }}">{{ field.label }}</label>
                </div>
                <div class="col-4 pr-0">
                    {{ field }}
                </div>
                <div class="col-3 text-center">
                    <!-- перебираем ошибки конкретного поля чтобы задать свои стили -->
                    {% for error in field.errors %}
                    <div class="alert alert-danger mb-0" style="padding: 0.375rem !important">{{ error }}</div>
                    {% endfor %}
                </div>
            </div>
            {% endfor %}
            <div class="row mt-3">
                <div class="col-6 pr-0">
                    <input class="btn btn-block btn-primary" type="submit" value="Обновить">
                    <a href="{% url 'main:vlan-delete' vlan.id %}?complex_slug={{ vlan.complex.slug }}" class="btn btn-block btn-danger">Удалить</i></a>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

web/main/templates/main/vlan/vlan.html
{% extends 'main/base.html' %}

{% block content %}
<h1 class="h3 mb-2 text-gray-800">{{ complex.name }}</h1>
<a href="{% url 'main:vlan-add' %}?complex_slug={{ complex.slug }}" class="btn btn-primary text-right">Добавить<i class="fas fa-plus ml-2"></i></a>
<table class="table table-sm table-striped table-bordered table-responsive mt-3">
    <thead class="thead-dark">
        <tr>
        <th scope="col" class="text-center" style="width: 80px;">Vlan</th>
        <th scope="col" class="text-center">Name</th>
        <th scope="col" class="text-center"></th>
        </tr>
    </thead>
    <tbody>
        <!-- перебираем все вланы в комплексе, сортируя по vlan_id -->
        {% for vlan in complex.vlan.all|dictsort:"vlan_id" %}
        <tr>
            <th scope="row" class="text-center align-middle">{{ vlan.vlan_id }}</th>
            <td style="min-width: 250px;">
                {{ vlan.name }}
            </td>
            <td class="text-center" style="min-width: 70px;">
                <a href="{% url 'main:vlan-update' vlan.id %}?complex_slug={{ complex.slug }}" class="btn-sm btn-warning">
                    Изменить<!--<i class="fas fa-pen"></i> -->
                </a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock content %}