web/main/urls.py
from django.urls import URLPattern, path
from main.views import equipment_views, port_views, vlan_views, views


app_name = 'main'
urlpatterns = [
    path('', views.index, name='index'),
    path('<slug:autozal_slug>/', views.autozal, name='autozal'),
    path('<slug:autozal_slug>/<int:rack_number>/', views.rack, name='rack'),
    path('<slug:autozal_slug>/<int:rack_number>/<str:place>', views.equipment, name='equipment-detail'),

    path('vlan/<slug:complex>/', views.vlan, name='vlan'),

    path('edit/equipment-add/', equipment_views.EquipmentAddView.as_view(), name='equipment-add'),
    path('edit/equipment-update/<int:pk>/', equipment_views.EquipmentUpdateView.as_view(), name='equipment-update'),
    path('edit/equipment-delete/<int:pk>/', equipment_views.EquipmentDeleteView.as_view(), name='equipment-delete'),

    path('edit/port-update/<int:pk>', port_views.port_update, name='port-update'),
    path('edit/port-clear/', port_views.port_clear, name='port-clear'),

    path('edit/vlan-add/', vlan_views.VlanAddView.as_view(), name='vlan-add'),
    path('edit/vlan-update/<int:pk>/', vlan_views.VlanUpdateView.as_view(), name='vlan-update'),
    path('edit/vlan-delete/<int:pk>/', vlan_views.VlanDeleteView.as_view(), name='vlan-delete'),

    path('ajax/port-dest/equip', port_views.get_equip_dropdown, name='port-dest-equip'),
    path('ajax/port-dest/ports', port_views.get_port_dropdown, name='port-dest-ports'),
]

web/main/forms/port_forms.py
from django.core.exceptions import ValidationError

from django import forms
from ..models import Equipment, Port, Rack, Vlan


class PortUpdateForm(forms.ModelForm):
    class Meta:
        model = Port
        fields = ['active', 'type', 'vlan', 'dest', 'full_path', 'desc']
        # делаем поле назначения не редактируемым, чтобы пользователь воспользовался
        # зависимыми dropdown для правильного выбора порта назначения
        widgets = {
            'dest': forms.TextInput(attrs={
                'readonly': '',
                'aria-label': 'destination',
                'aria-describedby': 'change_dest'
                })
        }

    def __init__(self, *args, **kwargs):
        # вытаскиваем из квагров id комплекса
        self.complex_id = kwargs.pop('complex_id')
        super().__init__(*args, **kwargs)
        # фильтруем queryset для отображения vlan только комплекса, к которому принадлежит оборудование
        self.fields['vlan'].queryset = Vlan.objects.filter(complex_id=self.complex_id)
        self.fields['vlan'].widget.attrs['style'] = 'display: none;'
        self.fields['desc'].widget.attrs['rows'] = 5
        # каждому полю формы прописываем класс 'form-control'
        for field_name, field in self.fields.items():
            if field_name == 'active':
                pass
            else:
                field.widget.attrs['class'] = 'form-control'
    

# форма зависимых полей для выбора нужного порта    
class DestinationPortUpdateForm(forms.Form):
    rack = forms.ModelChoiceField(queryset=Rack.objects.all(), label='Стойка откуда', initial='R', required=False, empty_label='Выберите стойку...',   widget=forms.Select(attrs={'class':'form-control'}))
    equip = forms.ModelChoiceField(queryset=Equipment.objects.all(), label='Оборудование откуда', required=False, empty_label='Выберите оборудование...', widget=forms.Select(attrs={'class':'form-control'}))
    port = forms.ModelChoiceField(queryset=Port.objects.all(), label='Порт откуда', required=False, empty_label='Выберите порт...', widget=forms.Select(attrs={'class':'form-control'}))
    

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['equip'].queryset = Equipment.objects.none()
        self.fields['port'].queryset = Port.objects.none()
        # проверяем что в запросе есть equip. если есть, то меняем queryset вместо пустого на фильтрованый,
        # чтобы не было ошибки заполнения поля. Так же делаем с port
        if self.data.get('equip'):
            equip_id = int(self.data.get('equip'))
            self.fields['equip'].queryset = Equipment.objects.filter(id=equip_id)
        if self.data.get('port'):
            port_id = int(self.data.get('port'))
            self.fields['port'].queryset = Port.objects.filter(id=port_id)
         

    def clean_port(self):
        port = self.cleaned_data['port']
        if port:
            if port.busy:
                raise ValidationError('Данный порт уже занят!')
        return port

web/main/views/port_views.py
from django.shortcuts import redirect, render

from ..models import Equipment, Port
from ..forms.port_forms import PortUpdateForm, DestinationPortUpdateForm
from ..functions.ports import port_dest_update, port_dest_clear


def port_update(request, pk):
    source_port = Port.objects.get(id=pk)
    # получаем id комплекса, чтобы передать его в форму, где vlan будут отфильтрованы по комплексу
    complex_id = source_port.equipment.complex.id
    # форма для редактирования информации о Порте
    source_port_form = PortUpdateForm(instance=source_port, complex_id=complex_id)
    # форма для зависимых select для выбора порта назначения
    dest_port_form = DestinationPortUpdateForm()
    if request.method == 'POST':
        source_port_form = PortUpdateForm(request.POST, instance=source_port, complex_id=complex_id)
        dest_port_form = DestinationPortUpdateForm(request.POST)
        if source_port_form.is_valid() and dest_port_form.is_valid():
            # если формы валидны, заполняем порт источник и порт назначения
            port_dest_update(request.POST, source_port)
            # сохраняем основную форму
            source_port_form.save()
            return redirect(
                'main:equipment-detail',
                autozal_slug=request.GET['autozal_slug'],
                rack_number=request.GET['rack_number'],
                place=request.GET['place'],
                )
    data = {
        'source_port_form': source_port_form,
        'dest_port_form': dest_port_form,
        'source_port': source_port
    }
    return render(request, 'main/ports/port-update.html', data)

# очищаем порт от описания, назначения и полного пути
def port_clear(request):
    port_dest_clear(request)
    return redirect(request.META['HTTP_REFERER'])

# возвращаем отфильтрованый select для выбора нужного оборудования в зависимости от стойки
def get_equip_dropdown(request):
    rack_id = request.GET.get('rack_id')
    equip = Equipment.objects.filter(rack_id=rack_id).order_by('place')
    return render(request, 'main/ports/equip-dropdown.html', {'equip': equip})

# возвращаем отфильтрованый select для выбора нужного порта в зависимости от оборудования
def get_port_dropdown(request):
    equip_id = request.GET.get('equip_id')
    ports = Port.objects.filter(equipment_id=equip_id).order_by('num')
    return render(request, 'main/ports/port-dropdown.html', {'ports': ports})

web/main/templates/main/ports/equip-dropdown.html
<!-- Шаблон для рендера зависимого select для выбора нужного оборудования -->
<option value="">Выберите оборудование...</option>
{% for item in equip %}
<option value="{{ item.id }}">{{ item }}</option>
{% endfor %}

web/main/templates/main/ports/port-dropdown.html
<!-- Шаблон для рендера зависимого select для выбора нужного порта -->
<option value="">Выберите порт...</option>
{% for item in ports %}
<option value="{{ item.id }}">{{ item.name }}</option>
{% endfor %}

web/main/templates/main/ports/port-update.html
{% extends 'main/base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/multi-select.css' %} ">
{% endblock css %}
{% block content %}
<h1 class="h3 mb-3 text-gray-800">Редактировать порт {{ source_port }}, id {{ source_port.id }}</h1>
<div class="row">
    <div class="col-12">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% for error in source_port_form.non_field_errors %}
            <div class="row mb-2 align-items-center">
                <div class="col-6 alert alert-danger">
                    {{ error }}
                </div>
            </div>
            {% endfor %}
            {% if dest_port_form.errors %}
            <div class="row mb-2 align-items-center">
                <div class="col-6 alert alert-danger">
                    {% for error in dest_port_form.port.errors %}
                        {{ error }}
                    {% endfor %}
                </div>
            </div>
            {% endif %}
            {% for field in source_port_form %}
            <div class="row mb-2 align-items-center">
                {% if source_port.equipment.type == 'switch' or  source_port.equipment.type == 'router'%}
                    {% include 'main/includes/port-active-equipment.html' %}
                {% elif source_port.equipment.type == 'operator' or source_port.equipment.type == 'unmanageble'%}
                    {% include 'main/includes/port-lite-edit.html' %}
                {% endif %}
            </div>
            {% endfor %} 
            <!-- Конец формы редактирования порта --> 
            <div class="row mt-3">
                <div class="col-6 pr-0">
                    <input class="btn btn-block btn-primary" type="submit" value="Сохранить">
                    <button type="button" class="btn btn-block btn-warning" data-toggle="modal" data-target="#exampleModal">
                        Очистить коммутацию
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Действительно хотите очистить коммутацию?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Отмена</button>
                <a href="{% url 'main:port-clear' %}?source_port_id={{ source_port.id }}&dest_port_id={{ source_port.dest_port_id }}" class="btn btn-primary">Очистить</a>
            </div>
        </div>
    </div>
</div>
{% endblock content %}
{% block scripts %}
<script src="{% static 'js/jquery.multi-select.js' %}"></script>
<script src="{% static 'js/script.js' %}"></script>
{% endblock scripts %}