web/main/urls.py
from django.urls import URLPattern, path
from main.views import equipment_views, port_views, vlan_views, views


app_name = 'main'
urlpatterns = [
    path('', views.index, name='index'),
    path('<slug:autozal_slug>/', views.autozal, name='autozal'),
    path('<slug:autozal_slug>/<int:rack_number>/', views.rack, name='rack'),
    path('<slug:autozal_slug>/<int:rack_number>/<str:place>', views.equipment, name='equipment-detail'),

    path('vlan/<slug:complex>/', views.vlan, name='vlan'),

    path('edit/equipment-add/', equipment_views.EquipmentAddView.as_view(), name='equipment-add'),
    path('edit/equipment-update/<int:pk>/', equipment_views.EquipmentUpdateView.as_view(), name='equipment-update'),
    path('edit/equipment-delete/<int:pk>/', equipment_views.EquipmentDeleteView.as_view(), name='equipment-delete'),

    path('edit/port-update/<int:pk>', port_views.port_update, name='port-update'),
    path('edit/port-clear/', port_views.port_clear, name='port-clear'),

    path('edit/vlan-add/', vlan_views.VlanAddView.as_view(), name='vlan-add'),
    path('edit/vlan-update/<int:pk>/', vlan_views.VlanUpdateView.as_view(), name='vlan-update'),
    path('edit/vlan-delete/<int:pk>/', vlan_views.VlanDeleteView.as_view(), name='vlan-delete'),

    path('ajax/port-dest/equip', port_views.get_equip_dropdown, name='port-dest-equip'),
    path('ajax/port-dest/ports', port_views.get_port_dropdown, name='port-dest-ports'),
]

web/main/views/equipment_views.py
from django.views.generic.edit import UpdateView, CreateView, DeleteView
from django.urls import reverse_lazy

from ..models import Equipment, Rack
from ..forms.equip_forms import EquipmentForm, EquipmentUpdateForm

# добавление оборудования
class EquipmentAddView(CreateView):
    model = Equipment
    template_name = 'main/equipment/equipment-add.html'
    form_class = EquipmentForm

    # подставляем в форму номер стойки, из которой была нажата кнопка "Добавить"
    def get_initial(self, **kwargs):
        initial = super(EquipmentAddView, self).get_initial(**kwargs)
        initial['rack'] = Rack.objects.get(number=self.request.GET['rack_number'])
        return initial
    
    # вытаскиваем GET параметры с номером текущей стойки и slug автозала
    def get_success_url(self, **kwargs):
        return reverse_lazy(
            'main:rack',
            args=[
                self.request.GET['autozal_slug'],
                self.request.GET['rack_number']
                ]
            )


# редактирование оборудования
class EquipmentUpdateView(UpdateView):
    model = Equipment
    template_name = 'main/equipment/equipment-update.html'
    form_class = EquipmentUpdateForm
    context_object_name = 'equip'

    # вытаскиваем GET параметры с номером текущей стойки и slug автозала
    def get_success_url(self, **kwargs):
        return reverse_lazy(
            'main:rack',
            args=[
                self.request.GET['autozal_slug'],
                self.request.GET['rack_number']
                ]
            )


# удаление оборудования
class EquipmentDeleteView(DeleteView):
    model = Equipment
    template_name = 'main/equipment/equipment-delete.html'
    context_object_name = 'equip'

    # вытаскиваем GET параметры с номером текущей стойки и slug автозала
    def get_success_url(self, **kwargs):
        return reverse_lazy(
            'main:rack',
            args=[
                self.request.GET['autozal_slug'],
                self.request.GET['rack_number']
                ]
            )
               

web/main/templates/main/equipment/equipment-add.html
{% extends 'main/base.html' %}

{% block content %}
<h1 class="h3 mb-3 text-gray-800">Добавить оборудование</h1>
<div class="row">
    <div class="col-12">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <!-- перебираем общие ошибки формы -->
            {% for error in form.non_field_errors %}
            <div class="row mb-2 align-items-center">
                <div class="col-6 alert alert-danger">
                    {{ error }}
                </div>
            </div>
            {% endfor %}
            <!-- перебираем саму форму -->
            {% for field in form %}
            <div class="row mb-2 align-items-center">
                <div class="col-2">
                    <label class="mb-0" for="{{ field.id_for_label }}">{{ field.label }}</label>
                </div>
                <div class="col-4 pr-0">
                    {{ field }}
                </div>
                <div class="col-3 text-center">
                    <!-- перебираем ошибки конкретного поля чтобы задать свои стили -->
                    {% for error in field.errors %}
                    <div class="alert alert-danger mb-0" style="padding: 0.375rem !important">{{ error }}</div>
                    {% endfor %}
                </div>
            </div>
            {% endfor %}
            <div class="row mt-3">
                <div class="col-6 pr-0">
                    <input class="btn btn-block btn-primary" type="submit" value="Добавить">
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

web/main/templates/main/equipment/equipment-delete.html
{% extends 'main/base.html' %}

{% block content %}
<h1 class="h3 mb-3 text-gray-800">Вы действительно хотите удалить оборудование {{ equip.name }}?</h1>
<form method="post">
    {% csrf_token %}
    <input type="submit" value="Удалить" class="btn btn-danger">
    <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-secondary">Назад</a>
</form>
{% endblock content %}

web/main/templates/main/equipment/equipment-detail.html
{% extends 'main/base.html' %}

{% block content %}
<h1 class="h3 mb-2 text-gray-800">Оборудование {{ rack.number }}-{{ equipment }} </h1>
<ul class="nav nav-tabs" id="myTab" role="tablist">
    <li class="nav-item" role="presentation">
        <a class="nav-link active" id="equip-tab" data-toggle="tab" href="#equip" role="tab" aria-controls="equip" aria-selected="true">Оборудование</a>
    </li>
    <li class="nav-item" role="presentation">
        <a class="nav-link" id="desc-tab" data-toggle="tab" href="#desc" role="tab" aria-controls="desc" aria-selected="false">Описание</a>
    </li>
</ul>

<div class="tab-content" id="myTabContent">
    <!-- Элемент вкладки Оборудование -->
    <div class="tab-pane fade mt-3 show active" id="equip" role="tabpanel" aria-labelledby="equip-tab">
        <table class="table table-responsive table-bordered table-striped table-sm mt-3 text-center">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">Interface</th>
                    {% if equipment.type == 'switch'%}
                    <th scope="col" style="min-width: 100px">Type</th>
                    <th scope="col" style="min-width: 70px">Vlan</th>
                    {% endif %}
                    <th scope="col" style="min-width: 100px">Destination</th>
                    <th scope="col" style="min-width: 200px">Description</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                <!-- перебор всех портов в оборудовании -->
                {% for port in equipment.ports.all %}
                <tr class="">
                    <!-- покраска ячейки порта в зависимости от его состояния -->
                    {% if port.active %}
                    <th scope="row" class="table-success">{{ port.name }}</th>
                    {% else %}
                    <th scope="row" class="table-danger">{{ port.name }}</th>
                    {% endif %}
                    {% if equipment.type == 'switch' %}
                    <td>{{ port.type }}</td>
                    <td>
                    <!-- вывод всех vlan на порту -->
                    {% for vlan in port.vlan.all %}
                        <!-- если элемент последний в списке, то запятую в конце не ставим-->
                        {% if forloop.last %}
                        {{ vlan.vlan_id }}
                        {% else %}
                        {{ vlan.vlan_id }},
                        {% endif %}
                    {% endfor %}
                    </td>
                    {% endif %}
                    <td>{{ port.dest }}</td>
                    <td class="text-center" >{{ port.desc }}</td>
                    <td class="text-center">
                        <!-- GET аргументы для того, чтобы передать в suссess_url нужные параметры -->
                        <a href="{% url 'main:port-update' port.id %}?autozal_slug={{ rack.autozal.slug }}&rack_number={{ rack.number }}&place={{ equipment.place }}" class="btn-sm btn-warning">
                            Изменить<!--<i class="fas fa-pen"></i> -->
                        </a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% comment %} {% endif %} {% endcomment %}
    </div>
    <!-- Конец элемента вкладки Оборудование -->
    <!-- Элемент вкладки Описание -->
    <div class="tab-pane fade mt-3" id="desc" role="tabpanel" aria-labelledby="desc-tab">
        Описание
    </div>
    <!-- Конец элемента вкладки Описание -->
</div>
{% endblock content %}

web/main/templates/main/equipment/equipment-update.html
{% extends 'main/base.html' %}

{% block content %}
<h1 class="h3 mb-3 text-gray-800">Редактировать оборудование</h1>
<div class="row">
    <div class="col-12">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <!-- перебираем общие ошибки формы -->
            {% for error in form.non_field_errors %}
            <div class="row mb-2 align-items-center">
                <div class="col-6 alert alert-danger">
                    {{ error }}
                </div>
            </div>
            {% endfor %}
            <!-- перебираем саму форму -->
            {% for field in form %}
            <div class="row mb-2 align-items-center">
                <div class="col-2">
                    <label class="mb-0" for="{{ field.id_for_label }}">{{ field.label }}</label>
                </div>
                <div class="col-4 pr-0">
                    {{ field }}
                </div>
                <div class="col-3 text-center">
                    <!-- перебираем ошибки конкретного поля чтобы задать свои стили -->
                    {% for error in field.errors %}
                    <div class="alert alert-danger mb-0" style="padding: 0.375rem !important">{{ error }}</div>
                    {% endfor %}
                </div>
            </div>
            {% endfor %}
            <div class="row mt-3">
                <div class="col-6 pr-0">
                    <input class="btn btn-block btn-primary" type="submit" value="Обновить">
                    <a href="{% url 'main:equipment-delete' equip.id %}?autozal_slug={{ equip.rack.autozal.slug }}&rack_number={{ equip.rack.number }}" class="btn btn-block btn-danger">Удалить</i></a>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock content %}